[package]
name = "pelican-core"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.16", features = ["ndarray", "autodiff"] }

[dev-dependencies]
burn = { version = "0.16", features = ["ndarray", "autodiff"] }
